# Generated by Django 2.0.7 on 2018-07-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=200, verbose_name='Mac Address')),
                ('date', models.DateTimeField(verbose_name='Fecha de Obtencion')),
                ('data', models.TextField(verbose_name='Mac Obtenidas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
                'ordering': ['date'],
            },
        ),
    ]
