# Generated by Django 2.0.7 on 2018-07-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldmenbers',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/pics/', verbose_name='Imagen'),
        ),
    ]
