# Generated by Django 2.0.7 on 2018-07-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
